export function TermsPage() {
  return (
    <div className="section-shell py-20 lg:py-32 max-w-4xl mx-auto prose prose-lg prose-invert prose-p:text-[#8e9787] prose-p:leading-relaxed prose-headings:text-[#f1f3e8]">
      <h1 className="text-5xl font-medium tracking-tight mb-8">Terms of Use</h1>
      <p className="text-sm font-mono text-[#687360] mb-12 uppercase tracking-wider">Last Updated: September 12, 2026</p>

      <div className="bg-[#d7ff32]/10 border border-[#d7ff32]/30 p-8 rounded-md mb-16 not-prose">
        <h3 className="text-[#d7ff32] font-mono font-bold uppercase tracking-widest text-sm mb-4">Crucial Disclaimer</h3>
        <p className="text-base text-[#e9ebdf] m-0 leading-relaxed">Isogate is an experimental technical demonstration. The interface provided is a deterministic simulation running locally in your browser. Simulated proof and certificate outputs generated by the console have no on-chain, cryptographic, or legal validity.</p>
      </div>

      <section className="mb-16">
        <h2 className="text-3xl font-medium mb-6 border-b border-[#d7ff32]/20 pb-4 text-[#efffca]">1. Nature of the Service</h2>
        <p>The Isogate platform ("the Service") currently consists of a frontend technical landing page and a local browser-based CPU simulation. It is designed to illustrate the concept of verifiable agent execution through NAND gate compilation.</p>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-medium mb-6 border-b border-[#d7ff32]/20 pb-4 text-[#efffca]">2. No Financial Advice or Offer</h2>
        <p>Nothing on this site constitutes financial advice, investment advice, or a solicitation to buy or sell any asset, token, or security. References to network economics, token models, staking, slashing, and execution on chains (e.g., "Robinhood Chain") are purely conceptual descriptions of future product direction.</p>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-medium mb-6 border-b border-[#d7ff32]/20 pb-4 text-[#efffca]">3. Affiliation</h2>
        <p>Isogate is an independent conceptual project. We do not claim any official partnership, deployment, or endorsement by Robinhood or Robinhood Chain. Any references to chain 4663 are illustrative.</p>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-medium mb-6 border-b border-[#d7ff32]/20 pb-4 text-[#efffca]">4. Warranties and Liability</h2>
        <p>The Service is provided "AS IS" and "AS AVAILABLE" without any warranty of any kind, express or implied. We do not guarantee that the simulation accurately represents final production cryptographic proofs or smart contract deployments. We are not liable for any damages arising from your use of, or inability to use, the demonstration.</p>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-medium mb-6 border-b border-[#d7ff32]/20 pb-4 text-[#efffca]">5. Acceptable Use</h2>
        <p>You may use the simulation to understand the Isogate architecture. You may not attempt to reverse engineer, disrupt, or attack the hosting infrastructure, nor use the simulated certificates to misrepresent cryptographic validity in real-world transactions.</p>
      </section>
    </div>
  );
}
